<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/Tasks/Tasks_types.php';

$GLOBALS['snaphappi_api_Tasks_CONSTANTS'] = array();

$GLOBALS['snaphappi_api_Tasks_CONSTANTS']['SNAPHAPPI_VERSION_MAJOR'] = 0;

$GLOBALS['snaphappi_api_Tasks_CONSTANTS']['SNAPHAPPI_VERSION_MINOR'] = 1;

?>
