/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Snaphappi {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;
import com.hurlant.math.BigInteger;

  public class Constants {

    public static const SNAPHAPPI_VERSION_MAJOR:int = int(0);

    public static const SNAPHAPPI_VERSION_MINOR:int = int(1);

  }
}
