/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Snaphappi 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class ErrorCode   {
    public static const Unknown:int = 1;
    public static const InvalidAuth:int = 2;
    public static const DataConflict:int = 3;

    public static const VALID_VALUES:Set = new Set(Unknown, InvalidAuth, DataConflict);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[Unknown] = "Unknown";
      VALUES_TO_NAMES[InvalidAuth] = "InvalidAuth";
      VALUES_TO_NAMES[DataConflict] = "DataConflict";

    }
  }
}
