/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Snaphappi 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class UploadType   {
    public static const Preview:int = 1;
    public static const Original:int = 2;

    public static const VALID_VALUES:Set = new Set(Preview, Original);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[Preview] = "Preview";
      VALUES_TO_NAMES[Original] = "Original";

    }
  }
}
